name: 'GitHub Workflow Cleaner Action'
author: 'Rokib Hasan Sagar'
description: 'Clean GitHub Workflow Environment For Lightweight Build Purpose'
inputs:
  retain:
    description: "Comma/Space-separated Values of Apps to Keep"
    default: ""
branding:
  icon: 'layers'
  color: 'green'
runs:
  using: "composite"
  steps:
    - name: 'Cleanup Operation'
      shell: bash
      run: |
        chmod a+x $GITHUB_ACTION_PATH/cleanup.sh
        bash $GITHUB_ACTION_PATH/cleanup.sh
      env:
        retain: "${{ inputs.retain }}"
